// Package gotool implements the Go extractor (PRD 3.1): it generates a small
// reflection-based program INSIDE the service module (under .wirefit/gen/),
// which makes `internal/` DTO packages importable — the resolution of the
// Phase 3 blocking question — and runs it with the service's own toolchain.
//
// Spec format in the manifest: "./relative/pkg#TypeName".
package gotool

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/wirefit/wirefit/internal/extract"
	"github.com/wirefit/wirefit/internal/extrun"
)

var moduleRe = regexp.MustCompile(`(?m)^module\s+(\S+)`)

var typeNameRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// IsSpec reports whether a manifest dto reference targets the Go extractor.
func IsSpec(dto string) bool {
	file, _, ok := strings.Cut(dto, "#")
	return ok && (strings.HasPrefix(file, "./") || file == ".")
}

// Extractor adapts the Go extractor to the extract registry.
type Extractor struct{}

func (Extractor) Match(ref string) bool { return IsSpec(ref) }

// Extract implements extract.Extractor. Go structs draw no input/output
// distinction, so roles are ignored.
func (Extractor) Extract(projectDir string, specs []extract.Spec) (map[string]json.RawMessage, error) {
	return Run(projectDir, extract.Refs(specs))
}

// Run extracts IR for the given specs by generating and running a program in
// the service module. Returns raw IR JSON keyed by spec.
func Run(projectDir string, specs []string) (map[string]json.RawMessage, error) {
	modBytes, err := os.ReadFile(filepath.Join(projectDir, "go.mod"))
	if err != nil {
		return nil, fmt.Errorf("go extractor: %s has no go.mod: %w", projectDir, err)
	}
	m := moduleRe.FindSubmatch(modBytes)
	if m == nil {
		return nil, fmt.Errorf("go extractor: cannot find module line in go.mod")
	}
	module := string(m[1])

	type target struct{ spec, importPath, typeName, alias string }
	var targets []target
	imports := map[string]string{} // importPath → alias
	sorted := append([]string(nil), specs...)
	sort.Strings(sorted)
	for i, spec := range sorted {
		file, typeName, _ := strings.Cut(spec, "#")
		if !typeNameRe.MatchString(typeName) {
			return nil, fmt.Errorf("go extractor: %s: type name %q must be a Go identifier", spec, typeName)
		}
		rel := strings.TrimPrefix(file, "./")
		ip := module
		if rel != "" && rel != "." {
			ip = module + "/" + path.Clean(rel)
		}
		alias, ok := imports[ip]
		if !ok {
			alias = fmt.Sprintf("p%d", i)
			imports[ip] = alias
		}
		targets = append(targets, target{spec, ip, typeName, alias})
	}

	var importLines, entryLines []string
	for ip, alias := range imports {
		importLines = append(importLines, fmt.Sprintf("\t%s %q", alias, ip))
	}
	sort.Strings(importLines)
	for _, t := range targets {
		entryLines = append(entryLines, fmt.Sprintf("\t%q: reflect.TypeOf((*%s.%s)(nil)).Elem(),", t.spec, t.alias, t.typeName))
	}

	genRoot := filepath.Join(projectDir, ".wirefit", "gen")
	src := strings.Replace(program, "//IMPORTS//", strings.Join(importLines, "\n"), 1)
	src = strings.Replace(src, "//TARGETS//", strings.Join(entryLines, "\n"), 1)
	var out map[string]json.RawMessage
	err = extrun.WithTempDir(genRoot, "extract-", func(dir string) error {
		if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(src), 0o644); err != nil {
			return err
		}
		cmd := exec.Command("go", "run", "./.wirefit/gen/"+filepath.Base(dir))
		cmd.Dir = projectDir
		var err error
		out, err = extrun.Run("go", cmd)
		return err
	})
	return out, err
}

// program is the generated reflection walker. Stdlib only; deterministic
// output (sorted keys via encoding/json map marshalling + sorted required).
//
// Mapping (documented in extractors/golang/README.md):
//
//	pointer → nullable · `,omitempty`/`,omitzero` → optional · plain value → required non-nullable
//	int/int8/16/32, uint8/16 → int32 · int64, uint32, time.Duration → int64
//	uint/uint64 → error (may exceed int64) · float32/float64 → float32/float64
//	string → string · bool → bool · []byte → bytes · time.Time → datetime
//	uuid.UUID (github.com/google/uuid) → uuid · map[string]T → open object
//	embedded Struct and *Struct → flattened (encoding/json promotion) · interfaces → error
const program = `package main

// generated by wirefit extract — do not commit (.wirefit/ is transient)

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"
//IMPORTS//
)

var targets = map[string]reflect.Type{
//TARGETS//
}

func fail(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "wirefit-extract-go: "+format+"\n", a...)
	os.Exit(2)
}

var (
	timeType = reflect.TypeOf(time.Time{})
	rawType  = reflect.TypeOf(json.RawMessage{})
)

func main() {
	out := map[string]any{}
	keys := make([]string, 0, len(targets))
	for k := range targets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, spec := range keys {
		out[spec] = schemaFor(targets[spec], nil, spec)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(out); err != nil {
		fail("%v", err)
	}
}

func scalar(s string) map[string]any {
	jt := map[string]string{"bool": "boolean", "int32": "integer", "int64": "integer",
		"float32": "number", "float64": "number", "decimal": "number"}[s]
	if jt == "" {
		jt = "string"
	}
	return map[string]any{"type": jt, "x-ct-scalar": s}
}

func schemaFor(t reflect.Type, stack []reflect.Type, ctx string) map[string]any {
	switch {
	case t == timeType:
		return scalar("datetime")
	case t.Name() == "UUID" && strings.HasSuffix(t.PkgPath(), "github.com/google/uuid"):
		return scalar("uuid")
	case t == rawType:
		fail("json.RawMessage at %s: opaque payloads cannot be contract-checked", ctx)
	}
	switch t.Kind() {
	case reflect.String:
		return scalar("string")
	case reflect.Bool:
		return scalar("bool")
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Uint8, reflect.Uint16:
		return scalar("int32")
	case reflect.Int64, reflect.Uint32:
		return scalar("int64")
	case reflect.Uint, reflect.Uint64:
		fail("%s at %s may exceed int64; use a signed type for contract fields", t.Kind(), ctx)
	case reflect.Float32:
		return scalar("float32")
	case reflect.Float64:
		return scalar("float64")
	case reflect.Pointer:
		inner := schemaFor(t.Elem(), stack, ctx)
		inner["x-ct-nullable"] = true
		return inner
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			return scalar("bytes")
		}
		return map[string]any{"type": "array", "items": schemaFor(t.Elem(), stack, ctx+"[]")}
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			fail("non-string map key at %s", ctx)
		}
		return map[string]any{"type": "object",
			"additionalProperties": schemaFor(t.Elem(), stack, ctx+"{}")}
	case reflect.Interface:
		fail("interface type at %s: Go has no checkable union representation yet (Phase 5 importers)", ctx)
	case reflect.Struct:
		for _, s := range stack {
			if s == t {
				return map[string]any{"x-ct-recursive": true}
			}
		}
		return structFor(t, append(stack, t), ctx)
	}
	fail("unsupported kind %s at %s", t.Kind(), ctx)
	return nil
}

type candidate struct {
	field    reflect.StructField
	depth    int
	tagged   bool
	optional bool
}

// pick applies encoding/json's promotion rules to the fields competing for one
// JSON name: shallowest depth wins, a tie is broken by a json tag, and an
// unbroken tie has no winner. encoding/json drops that last case silently; a
// contract cannot afford to, so structFor fails on it instead.
func pick(cands []candidate) (candidate, bool) {
	shallowest := cands[0].depth
	for _, c := range cands {
		if c.depth < shallowest {
			shallowest = c.depth
		}
	}
	var top []candidate
	for _, c := range cands {
		if c.depth == shallowest {
			top = append(top, c)
		}
	}
	if len(top) > 1 {
		var tagged []candidate
		for _, c := range top {
			if c.tagged {
				tagged = append(tagged, c)
			}
		}
		top = tagged
	}
	if len(top) != 1 {
		return candidate{}, false
	}
	return top[0], true
}

func structFor(t reflect.Type, stack []reflect.Type, ctx string) map[string]any {
	cands := map[string][]candidate{}
	var order []string

	type level struct {
		t        reflect.Type
		depth    int
		optional bool
	}
	// Breadth-first so that depth, which decides promotion conflicts, is known
	// when each candidate is recorded.
	visited := map[reflect.Type]bool{t: true}
	queue := []level{{t, 0, false}}
	for len(queue) > 0 {
		var next []level
		for _, q := range queue {
			for i := 0; i < q.t.NumField(); i++ {
				f := q.t.Field(i)
				ft := f.Type
				if f.Anonymous && ft.Kind() == reflect.Pointer {
					ft = ft.Elem()
				}
				if f.Anonymous {
					// An embedded unexported struct type still promotes its own
					// exported fields.
					if !f.IsExported() && ft.Kind() != reflect.Struct {
						continue
					}
				} else if !f.IsExported() {
					continue
				}
				tag := f.Tag.Get("json")
				if tag == "-" {
					continue
				}
				name, opts, _ := strings.Cut(tag, ",")
				if f.Anonymous && name == "" && ft.Kind() == reflect.Struct {
					if !visited[ft] {
						visited[ft] = true
						// A nil embedded pointer emits none of the fields it
						// promotes, so they cannot be required.
						next = append(next, level{ft, q.depth + 1, q.optional || f.Type.Kind() == reflect.Pointer})
					}
					continue
				}
				tagged := name != ""
				if !tagged {
					name = f.Name
				}
				optional := q.optional
				for _, o := range strings.Split(opts, ",") {
					if o == "omitempty" || o == "omitzero" {
						optional = true
					}
					if o == "string" {
						fail("json \"string\" option at %s.%s: quoted numbers change the wire type", ctx, name)
					}
				}
				if _, seen := cands[name]; !seen {
					order = append(order, name)
				}
				cands[name] = append(cands[name], candidate{f, q.depth, tagged, optional})
			}
		}
		queue = next
	}

	props := map[string]any{}
	var required []string
	for _, name := range order {
		win, ok := pick(cands[name])
		if !ok {
			fail("ambiguous field %q at %s: embedded promotion leaves no single winner", name, ctx)
		}
		props[name] = schemaFor(win.field.Type, stack, ctx+"."+name)
		if !win.optional {
			required = append(required, name)
		}
	}
	if len(props) == 0 {
		fail("struct with no serializable fields at %s (%s)", ctx, t)
	}
	node := map[string]any{"type": "object", "properties": props}
	if len(required) > 0 {
		sort.Strings(required)
		node["required"] = required
	}
	return node
}
`
